### PR TITLE
Add PlatformIO Library Registry manifest file

### PR DESCRIPTION
**Pull request by gandy92**
- Add library.json files for the three libraries; this allows the libraries 
  to be managed from within PlatformIO (see http://platformio.org/)

### CODE REVIEW

**Comment by gandy92** [comment]
Thank you for accepting my merge request. The PlatformIO Library Registry manifest files have already been registered with platformio, please check http://platformio.org/#!/lib/search?query=Thijs&page=1 for details.

**Comment by thijse** [comment]
Sure, no problem. PlatformIO sounds cool!

What does it mean that the non Arduino folders are on the ignore list, are
they not fetched? They are pretty useful to have.

Thijs

**Comment by thijse** [comment]
Oh, and another question: I've been added as Thijs Elenb, but that should
be Thijs Elenbaas. Is there a way I can change my profile?

Thijs

**Comment by gandy92** [comment]
Oh yes, PlatformIO is cool :-) @ivankravets did a real great job, he will love your feedback! 

Actually, the non-arduino folders are not on the ignore list, I just did not add a library.json file for them. 

I was assigned with the task of adding top github libraries to the platformio library manager. Some of the search results turn out not to be a library at all, at least none I can use with platformio - these I do add to my ignore list. Before writing a new library.json file I examine the library file structure and if it appears to be rather complex I tend to go on to the next library. Also, if I fail to compile the library with platformio (using the arduino framework) I do the same. Normally. I would add a comment to my list to revisit later. 

If you are excited about platformio and you want to support the effort, maybe you can add the library.json files yourself? As library owner, you are in the best position to do so :smile: 
Before doing so, you may want to create a test project with ```platformio init -b BOARDNAME``` (you can get a list of supported boards with ```platformio boards```), copy the library to the ```lib/``` directory and an example to the ```src/``` directory. 

If you need assistance in writing the library.json file, please let me know. You can find an introduction at http://docs.platformio.org/en/latest/librarymanager/creating.html

Pertaining your name: The PlatformIO library crawler scans the github websites to automatically fill in the unspecified fields. Probably you can specify your name in the library.json file by explicitly stating ```author``` in the manifest file. If you update your github profile, the library information should be updated automatically within the next 24 hours.

**Pull request merged**
